#!/usr/bin/env python3
"""Generate cross-validation vectors for fir_core.

For each filter (16-tap and 32-tap low-pass), we:
  1. Build a Hamming-windowed sinc low-pass with cutoff = 0.25*Fs.
  2. Quantise the coefficients to int16 Q1.15 (sum = 2**15 = unity DC gain).
  3. Run scipy.signal.lfilter on a deterministic random int16 input stream
     (length 256), then quantise the output back to int16 with the
     same arithmetic-shift convention as the RTL (>>> 15, then saturate).
  4. Emit the data as a C header consumed by sim_main.cpp.

Re-run with:  make regen_vectors
"""

from __future__ import annotations
import sys
import numpy as np
from scipy.signal import firwin, lfilter

SEED = 0xF112_C0DE
INPUT_LEN = 256


def design_lowpass(n_taps: int, cutoff: float = 0.25) -> np.ndarray:
    """Hamming-windowed FIR low-pass, then quantised to Q1.15 int16.

    Coefficients are scaled so that sum(taps) == 2**15 (unity DC gain
    in the integer domain).
    """
    # firwin returns float coefficients with sum ~= 1.0 (unity DC gain).
    h = firwin(n_taps, cutoff, window="hamming")
    h = h / np.sum(h)                       # exact unity DC gain
    h_q = np.round(h * (1 << 15)).astype(np.int64)
    # Re-normalise so the integer sum is exactly 2**15 (rounding may
    # have moved it by +/- a few units).
    drift = (1 << 15) - int(np.sum(h_q))
    if drift != 0:
        # Distribute the drift onto the largest tap so we don't ruin
        # the symmetry.
        idx = int(np.argmax(np.abs(h_q)))
        h_q[idx] += drift
    return h_q.astype(np.int16)


def saturate_to_int16(x: np.ndarray) -> np.ndarray:
    return np.clip(x, -32768, 32767).astype(np.int16)


def reference_filter(h: np.ndarray, x: np.ndarray) -> np.ndarray:
    """Bit-exact integer reference matching the RTL pipeline.

    scipy.signal.lfilter does not accept integer dtypes; we run it in
    float64 (large enough for 16-bit data * 16-bit coeff * 32-tap sum
    without precision loss, since 32 * 2^15 * 2^15 = 2**35 << 2**52
    mantissa) and cross-check with a hand-rolled integer convolution.
    Both paths must agree exactly.
    """
    h64 = h.astype(np.int64)
    x64 = x.astype(np.int64)

    # Hand-rolled integer convolution (causal, zero state).
    n_taps = len(h64)
    y_int = np.zeros(len(x64), dtype=np.int64)
    for n in range(len(x64)):
        acc = np.int64(0)
        for k in range(n_taps):
            if n - k >= 0:
                acc += h64[k] * x64[n - k]
        y_int[n] = acc

    # scipy float reference for cross-check.
    y_float = lfilter(h.astype(np.float64), [1.0], x.astype(np.float64))
    # The float result may differ from the int by < 1 ULP; round and
    # compare to be safe.
    y_float_int = np.round(y_float).astype(np.int64)
    if not np.array_equal(y_int, y_float_int):
        # Print first mismatch for debugging.
        diff = np.where(y_int != y_float_int)[0]
        raise RuntimeError(
            f"int and float references disagree at index {diff[0]}: "
            f"int={y_int[diff[0]]}  float_round={y_float_int[diff[0]]}"
        )

    # Arithmetic right shift by 15 (Q1.15 -> integer).
    y_shifted = y_int >> 15
    return saturate_to_int16(y_shifted)


def random_input(rng: np.random.Generator) -> np.ndarray:
    return rng.integers(-32768, 32768, size=INPUT_LEN, dtype=np.int64).astype(
        np.int16
    )


def emit_array(name: str, arr: np.ndarray, ctype: str) -> str:
    body = ", ".join(f"{int(v):d}" for v in arr.astype(np.int64))
    return f"static const {ctype} {name}[{len(arr)}] = {{ {body} }};\n"


def main() -> None:
    rng = np.random.default_rng(SEED)
    h16 = design_lowpass(16)
    h32 = design_lowpass(32)
    x   = random_input(rng)

    y16 = reference_filter(h16, x)
    y32 = reference_filter(h32, x)

    # Saturation test vector: deliberately unscaled coefficients (all
    # equal to 32767, the maximum positive Q1.15 value). Sum >> 15
    # quickly exceeds int16 range when the input is at the rail, which
    # forces sat_hi / sat_lo through the SVA `p_output_bounded`.
    h_sat = np.full(16, 32767, dtype=np.int16)
    x_sat = np.full(INPUT_LEN, 32767, dtype=np.int16)
    x_sat[INPUT_LEN // 2 :] = -32768
    y_sat = reference_filter(h_sat, x_sat)

    out = []
    out.append(
        "// SPDX-License-Identifier: GPL-3.0-or-later OR Commercial\n"
    )
    out.append("// Auto-generated by tb/gen_random_vectors.py.\n")
    out.append("// Do not edit; regenerate with `make regen_vectors`.\n\n")
    out.append("#pragma once\n")
    out.append("#include <cstdint>\n\n")
    out.append(f"static constexpr int kFirInputLen = {INPUT_LEN};\n\n")

    out.append(emit_array("kFirH16",  h16,  "int16_t"))
    out.append(emit_array("kFirH32",  h32,  "int16_t"))
    out.append(emit_array("kFirIn",   x,    "int16_t"))
    out.append(emit_array("kFirOut16",y16,  "int16_t"))
    out.append(emit_array("kFirOut32",y32,  "int16_t"))

    out.append(emit_array("kFirHSat",  h_sat, "int16_t"))
    out.append(emit_array("kFirInSat", x_sat, "int16_t"))
    out.append(emit_array("kFirOutSat",y_sat, "int16_t"))

    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
